# Generated by Django 5.1.3 on 2025-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="model",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
